### ISSUE TITLE
大佬你好，我也试着在编译k3的固件，遇到了两个问题希望大佬不吝赐教

### ISSUE THREAD

**Issue by weigeloveu** [xiangfeidexiaohuo/AE86Wrt#1]
大佬你好，我是一个小白正在尝试编译k3的固件，遇到了两个问题希望大佬不吝赐教：
在搜索问题的时候无意间发现了您的项目，在此先行谢过了
1.lede源码编译会生成许多其无关他机型的刷机包，导致action最后的文件非常巨大，不知道大佬是怎么解决的。
2.其中有个“CPU 性能优化调节设置”的插件，编译完之后发现设置里工作模式跟频率都只有一档，是我编译的时候有什么地方遗漏了没勾选上吗？
3.我翻看了您git升级记录，config升级您是怎么做到的，手动配置完了再替换吗？还是有啥办法能同步源码更新？

**Comment by xiangfeidexiaohuo** [comment]
k3有命令直接只编译k3的，不编译其他的bcm53xx

sed -i 's|^TARGET_|# TARGET_|g; s|# TARGET_DEVICES += phicomm-k3|TARGET_DEVICES += phicomm-k3| ; s|# TARGET_DEVICES += phicomm_k3|TARGET_DEVICES += phicomm_k3|' target/linux/bcm53xx/image/Makefile

**Comment by xiangfeidexiaohuo** [comment]
至于那个cpu调节，要这个插件有适配你编译的机器，毕竟这个玩意不是统配。

至于config，可以手动配置再替换，也可以直接写某个（前提是你知道咋写）。
