### ISSUE TITLE
最近几个版本AX6的固件启动不了，回到7月7号版本才行。

### ISSUE THREAD

**Issue by PlumWolf** [xiangfeidexiaohuo/AE86Wrt#13]
最近几个版本AX6的固件启动不了，回到7月7号版本才行。

**Comment by xiangfeidexiaohuo** [comment]
> 最近几个版本AX6的固件启动不了，回到7月7号版本才行。

常理 714 应该没问题啊，721同步了最新的源码，721之前的 又没
