### ISSUE TITLE
AX3600，1124版本固件问题

### ISSUE THREAD

**Issue by esports612** [xiangfeidexiaohuo/AE86Wrt#14]
你好，我的AX3600使用了1124版本的固件，但使用一段时间后，总会出现无法更改设置的情况。具体表现为更改设置后，点击应用&保存，页面会自动恢复成更改前的设置，导致无法更改设置。请问如何解决呢？谢谢

**Comment by esports612** [comment]
PS，每次出现这个问题，只有重置才会恢复正常，日常使用中只使用了SS和adguard home这2个功能，最近一次重置是在12月11日，今天18日这个问题又发生了

**Comment by xiangfeidexiaohuo** [comment]
> PS，每次出现这个问题，只有重置才会恢复正常，日常使用中只使用了SS和adguard home这2个功能，最近一次重置是在12月11日，今天18日这个问题又发生了

这是因为空间不足，导致的
你可以时刻关注 软件包 里的空闲空间
基本你这个是 剩余空间为0 就只能重置

adg 使用请关闭日志，大量日志会很占空间

**Comment by esports612** [comment]
好的，我关注一下，谢谢
