### ISSUE TITLE
小米AX3600，请问哪个版本的固件，SS可以批量导入节点信息？

### ISSUE THREAD

**Issue by esports612** [xiangfeidexiaohuo/AE86Wrt#17]
小米AX3600，请问哪个版本的固件，SS可以批量导入节点信息？目前使用的是20231222版本，1个个导入节点信息有点不方便，谢谢

**Comment by xiangfeidexiaohuo** [comment]
> 小米AX3600，请问哪个版本的固件，SS可以批量导入节点信息？目前使用的是20231222版本，1个个导入节点信息有点不方便，谢谢

重新用uboot 刷个新的 515 呗 就成
