### ISSUE TITLE
缺少luci-lip-ipkg

### ISSUE THREAD

**Issue by HiJwm** [xiangfeidexiaohuo/AE86Wrt#3]
老大，提示缺少luci-lip-ipkg怎么解决呢

**Comment by xiangfeidexiaohuo** [comment]
> 老大，提示缺少luci-lip-ipkg怎么解决呢

如果是用的Lean的源码，缺这个的话，只需要加个空包就好。https://github.com/xiangfeidexiaohuo/op-ipkg
