### ISSUE TITLE
Redmi AX6000每隔半小时左右就会满载然后断网

### ISSUE THREAD

**Issue by Kelcoin** [xiangfeidexiaohuo/AE86Wrt#7]
![image](https://user-images.githubusercontent.com/10922375/193622349-d5491349-57ef-4ca2-ae73-970d274fa911.png)
如图，每半个小时左右负载就会升高

**Comment by Kelcoin** [comment]
![BSG_3{SPSM@9S738U4(8I42](https://user-images.githubusercontent.com/10922375/193628078-839fa7a4-7a82-4629-97a1-e9adef357929.png)
高负载时的进程信息

**Comment by xiangfeidexiaohuo** [comment]
> ![BSG_3{SPSM@9S738U4(8I42](https://user-images.githubusercontent.com/10922375/193628078-839fa7a4-7a82-4629-97a1-e9adef357929.png) 高负载时的进程信息

这就很迷，你是从x-wrt直接刷过来的吗，那个啥新分区，没问题是吧，单说 刷入。

**Comment by xiangfeidexiaohuo** [comment]
应该是启用了  sfe的锅，是mtk的芯片，不应该启用这个玩意
我会触发编译新版本，到时候你可以再看看

**Comment by Kelcoin** [comment]
> 应该是启用了 sfe的锅，是mtk的芯片，不应该启用这个玩意 我会触发编译新版本，到时候你可以再看看

我是从initramfs-factory全新刷入的，我在发现这个问题后就关闭了负载均衡和sfe，不过不起作用，我目前是关闭了fullcone nat，能缓解这个问题，但偶尔还是会断一下，很迷
至于触发点，两个可能的点是时间在15分左右和45分左右，或者是活动连接数到一万以上

**Comment by xiangfeidexiaohuo** [comment]
> 

你等会 看看新版本，猜应该是mtk启用了 sfe的问题，mtk不是启用这个玩意，我改了。大概12点多 能出来。主界面的，温度什么的 信息正确吗。

**Comment by xiangfeidexiaohuo** [comment]
> > 应该是启用了 sfe的锅，是mtk的芯片，不应该启用这个玩意 我会触发编译新版本，到时候你可以再看看
> 
> 我是从initramfs-factory全新刷入的，我在发现这个问题后就关闭了负载均衡和sfe，不过不起作用，我目前是关闭了fullcone nat，能缓解这个问题，但偶尔还是会断一下，很迷 至于触发点，两个可能的点是时间在15分左右和45分左右，或者是活动连接数到一万以上

试试  https://github.com/xiangfeidexiaohuo/OpenWrt_Build/releases/tag/202210041205

**Comment by Kelcoin** [comment]
> > > 应该是启用了 sfe的锅，是mtk的芯片，不应该启用这个玩意 我会触发编译新版本，到时候你可以再看看
> > 
> > 
> > 我是从initramfs-factory全新刷入的，我在发现这个问题后就关闭了负载均衡和sfe，不过不起作用，我目前是关闭了fullcone nat，能缓解这个问题，但偶尔还是会断一下，很迷 至于触发点，两个可能的点是时间在15分左右和45分左右，或者是活动连接数到一万以上
> 
> 试试 https://github.com/xiangfeidexiaohuo/OpenWrt_Build/releases/tag/202210041205

![image](https://user-images.githubusercontent.com/10922375/193758798-305f8256-c7cb-46cb-9083-e8dcf5d9f5c8.png)
还是一样的问题

**Comment by xiangfeidexiaohuo** [comment]
> > > > 应该是启用了 sfe的锅，是mtk的芯片，不应该启用这个玩意 我会触发编译新版本，到时候你可以再看看
> > > 
> > > 
> > > 我是从initramfs-factory全新刷入的，我在发现这个问题后就关闭了负载均衡和sfe，不过不起作用，我目前是关闭了fullcone nat，能缓解这个问题，但偶尔还是会断一下，很迷 至于触发点，两个可能的点是时间在15分左右和45分左右，或者是活动连接数到一万以上
> > 
> > 
> > 试试 https://github.com/xiangfeidexiaohuo/OpenWrt_Build/releases/tag/202210041205
> 
> ![image](https://user-images.githubusercontent.com/10922375/193758798-305f8256-c7cb-46cb-9083-e8dcf5d9f5c8.png) 还是一样的问题

我手动编译的 最后一个测试版，还有问题，我也无解，同步了大雕最新的源码。

AX6000_Redmi
https://www.aliyundrive.com/s/SHP6NN7PB99
提取码: 9527

有问题就去这里 https://github.com/coolsnowwolf/lede 反馈  看他那边怎么说，或者你提供日志上去。

**Comment by xiangfeidexiaohuo** [comment]
试过吗，还是有问题？ @Kelcoin
