### ISSUE TITLE
本地编译redmi-ax6固件   在编译nss/qca-nss-clients-64时报错缺少bonding.ko依赖

### ISSUE THREAD

**Issue by xbins7210** [xiangfeidexiaohuo/AE86Wrt#9]
大佬，我在使用您的【https://github.com/xiangfeidexiaohuo/lede】这个项目编译redmi-ax6的时候报错，信息如下，请教一下如何解决呢？
make[3]: Entering directory '/home/xcaptain/lede/package/qca/firmware/nss-firmware'
mkdir -p /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp
SHELL= flock /home/xcaptain/lede/tmp/.root-copy.flock -c 'cp -fpR /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/nss-firmware-2021-03-12-73f378d6/.pkgdir/nss-firmware-ipq8074/. /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.nss-firmware-ipq8074_installed
echo "nss-firmware-ipq8074" >> /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/nss-firmware.default.install
make[3]: Leaving directory '/home/xcaptain/lede/package/qca/firmware/nss-firmware'
time: package/qca/firmware/nss-firmware/compile#0.21#0.09#0.28
make[3]: Entering directory '/home/xcaptain/lede/package/qca/qca-ssdk'
mkdir -p /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp
SHELL= flock /home/xcaptain/lede/tmp/.root-copy.flock -c 'cp -fpR /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-ssdk-nohnat/qca-ssdk-2022-02-09-0d6d4106/.pkgdir/kmod-qca-ssdk-nohnat/. /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.kmod-qca-ssdk-nohnat_installed
echo "kmod-qca-ssdk-nohnat" >> /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/qca-ssdk.nohnat.install
make[3]: Leaving directory '/home/xcaptain/lede/package/qca/qca-ssdk'
time: package/qca/qca-ssdk/nohnat/compile#0.14#0.08#0.21
make[3]: Entering directory '/home/xcaptain/lede/package/qca/nss/qca-nss-dp'
mkdir -p /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp
SHELL= flock /home/xcaptain/lede/tmp/.root-copy.flock -c 'cp -fpR /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-dp-2022-04-30-72e9ec41/.pkgdir/kmod-qca-nss-dp/. /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.kmod-qca-nss-dp_installed
echo "kmod-qca-nss-dp" >> /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/qca-nss-dp.default.install
make[3]: Leaving directory '/home/xcaptain/lede/package/qca/nss/qca-nss-dp'
time: package/qca/nss/qca-nss-dp/compile#0.28#0.08#0.34
make[3]: Entering directory '/home/xcaptain/lede/package/qca/nss/qca-nss-drv-64'
mkdir -p /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp
SHELL= flock /home/xcaptain/lede/tmp/.root-copy.flock -c 'cp -fpR /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-drv-64-2022-01-24-4f1b8e51/.pkgdir/kmod-qca-nss-drv-64/. /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.kmod-qca-nss-drv-64_installed
echo "kmod-qca-nss-drv-64" >> /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/qca-nss-drv-64.default.install
make[3]: Leaving directory '/home/xcaptain/lede/package/qca/nss/qca-nss-drv-64'
time: package/qca/nss/qca-nss-drv-64/compile#0.28#0.09#0.35
make[3]: Entering directory '/home/xcaptain/lede/package/qca/nss/qca-nss-clients-64'
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.prepared_60e36bdf714eeb7a30ec7bfc3bb119c2_6664517399ebbbc92a37c5bb081b5c53_check
. /home/xcaptain/lede/include/shell.sh; xzcat /home/xcaptain/lede/dl/qca-nss-clients-64-2021-04-29-b93c72c1.tar.xz | tar -C /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.prepared_60e36bdf714eeb7a30ec7bfc3bb119c2_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.configured_*
rm -f /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.qca-nss-clients-64_installed
(cd /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/./; if [ -x ./configure ]; then find /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ -name config.guess | xargs -r chmod u+w; find /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ -name config.guess | xargs -r -n1 cp --remove-destination /home/xcaptain/lede/scripts/config.guess; find /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ -name config.sub | xargs -r chmod u+w; find /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ -name config.sub | xargs -r -n1 cp --remove-destination /home/xcaptain/lede/scripts/config.sub; AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1=qca-nss-clients-64-2021-04-29-b93c72c1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1=qca-nss-clients-64-2021-04-29-b93c72c1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-drv -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-crypto -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-cfi -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-gmac -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk/fal -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/nat46" CXXFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1=qca-nss-clients-64-2021-04-29-b93c72c1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-drv -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-crypto -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-cfi -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-gmac -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk/fal -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/nat46" CPPFLAGS="-I/home/xcaptain/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/include -I/home/xcaptain/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/include/fortify -I/home/xcaptain/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/include " LDFLAGS="-L/home/xcaptain/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/lib -L/home/xcaptain/lede/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/lib -znow -zrelro "   ./configure --target=aarch64-openwrt-linux --host=aarch64-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.built
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.built_check
make -C "/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.15.91" pppoe=y bridge-mgr=y vlan-mgr=y CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" M="/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1" EXTRA_CFLAGS="-I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-drv -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-crypto -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-cfi -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-gmac -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk/fal -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/usr/include/nat46" SoC="ipq807x_64" KCFLAGS="-fmacro-prefix-map=/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/xcaptain/lede/staging_dir/host/include -I/home/xcaptain/lede/staging_dir/hostpkg/include -I/home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Feb  9 13:11:58 2023" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/xcaptain/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/cryptodev-linux.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/fullconenat.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/gpio-button-hotplug.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/ksmbd.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/mac80211.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/qca-nss-clients-64.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/qca-nss-dp.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/qca-nss-drv-64.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/qca-ssdk.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/shortcut-fe-simulated-driver.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/shortcut-fe.symvers" KERNELRELEASE=5.15.91 modules
make[4]: Entering directory '/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.15.91'
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/bridge/nss_bridge_mgr.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/bridge/qca-nss-bridge-mgr.o
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/vlan/nss_vlan_mgr.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/vlan/qca-nss-vlan.o
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/nss_connmgr_pppoe.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/qca-nss-pppoe.o
  MODPOST /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/bridge/qca-nss-bridge-mgr.mod.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/bridge/qca-nss-bridge-mgr.ko
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/qca-nss-pppoe.mod.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/pppoe/qca-nss-pppoe.ko
  CC [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/vlan/qca-nss-vlan.mod.o
  LD [M]  /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/vlan/qca-nss-vlan.ko
make[4]: Leaving directory '/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/linux-5.15.91'
for subdir in .; do realdir=$(readlink -f /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1); grep -F /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1 /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/$subdir/Module.symvers >> /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers.tmp; [ "/home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1" = "$realdir" ] || grep -F $realdir /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/$subdir/Module.symvers >> /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers.tmp; done; sort -u /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers.tmp > /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers; mkdir -p /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers; mv /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/Module.symvers /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/symvers/qca-nss-clients-64.symvers
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.built
rm -rf /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64.installed /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64
mkdir -p /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64
mkdir -p /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64/etc/modules.d; ( echo "qca-nss-pppoe"; ) > /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64/etc/modules.d/51-qca-nss-drv-pppoe-64; 
touch /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64.installed
mkdir -p /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp
SHELL= flock /home/xcaptain/lede/tmp/.root-copy.flock -c 'cp -fpR /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/.pkgdir/kmod-qca-nss-drv-pppoe-64/. /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/'
touch /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/root-ipq807x/stamp/.kmod-qca-nss-drv-pppoe-64_installed
mkdir -p /home/xcaptain/lede/bin/targets/ipq807x/generic/packages /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ipkg-aarch64_cortex-a53/kmod-qca-nss-drv-pppoe-64/CONTROL /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/pkginfo
mkdir -p /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ipkg-aarch64_cortex-a53/kmod-qca-nss-drv-pppoe-64/etc/modules.d; ( echo "qca-nss-pppoe"; ) > /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ipkg-aarch64_cortex-a53/kmod-qca-nss-drv-pppoe-64/etc/modules.d/51-qca-nss-drv-pppoe-64; 
find /home/xcaptain/lede/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-64-2021-04-29-b93c72c1/ipkg-aarch64_cortex-a53/kmod-qca-nss-drv-pppoe-64 -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package kmod-qca-nss-drv-pppoe-64 is missing dependencies for the following libraries:
bonding.ko
make[3]: *** [Makefile:105: /home/xcaptain/lede/bin/targets/ipq807x/generic/packages/kmod-qca-nss-drv-pppoe-64_5.15.91+2021-04-29-b93c72c1-3_aarch64_cortex-a53.ipk] Error 1
make[3]: Leaving directory '/home/xcaptain/lede/package/qca/nss/qca-nss-clients-64'
time: package/qca/nss/qca-nss-clients-64/compile#3.84#0.80#4.60
    ERROR: package/qca/nss/qca-nss-clients-64 failed to build.
make[2]: *** [package/Makefile:116: package/qca/nss/qca-nss-clients-64/compile] Error 1
make[2]: Leaving directory '/home/xcaptain/lede'
make[1]: *** [package/Makefile:110: /home/xcaptain/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xcaptain/lede'
make: *** [/home/xcaptain/lede/include/toplevel.mk:231：world] 错误 2

查看makefile文件，也没看到有关bonding.ko的依赖：
localhost@debian:~/lede$ cat /home/xcaptain/lede/package/qca/nss/qca-nss-clients-64/Makefile 
include $(TOPDIR)/rules.mk

PKG_NAME:=qca-nss-clients-64
PKG_RELEASE:=$(AUTORELEASE)

PKG_SOURCE_URL:=https://source.codeaurora.org/quic/cc-qrdk/oss/lklm/nss-clients
PKG_SOURCE_PROTO:=git
PKG_SOURCE_DATE:=2021-04-29
PKG_SOURCE_VERSION:=b93c72c1b72c591c2ddc2f0b24f0e2b457720118
PKG_MIRROR_HASH:=fbfba64a364b095ea7c9a24cd7af96b63ab0bc29c179e1628c675aa223c0d063

include $(INCLUDE_DIR)/kernel.mk
include $(INCLUDE_DIR)/package.mk

define KernelPackage/qca-nss-drv-pppoe-64
  SECTION:=kernel
  CATEGORY:=Kernel modules
  SUBMENU:=Network Devices
  TITLE:=Kernel driver for NSS (connection manager) - PPPoE
  DEPENDS:=@(TARGET_ipq60xx||TARGET_ipq807x) +kmod-qca-nss-drv-64 +kmod-ppp +kmod-pppoe
  FILES:=$(PKG_BUILD_DIR)/pppoe/qca-nss-pppoe.ko
  AUTOLOAD:=$(call AutoLoad,51,qca-nss-pppoe)
endef

define KernelPackage/qca-nss-drv-pppoe-64/Description
Kernel modules for NSS connection manager - Support for PPPoE
endef
...

**Comment by xiangfeidexiaohuo** [comment]
你可能需要重新拉一遍源码，删除旧的，应该是上游 哪里动了。我后面重新调整过，但是你这边源码还是老的。

**Comment by xbins7210** [comment]
好的  谢谢大佬   我试试！
